public class BIDIMENSIONAL 
{

    public static void main(String[] args) 
    {
        
        
        String[][] asientos = 
        {
            {"A11", "A12"},
            {"B11", "B12"}
          
        };
        System.out.println("El asiento [0][0] es " + asientos[0][0]);
        System.out.println("El asiento [0][0] es " + asientos[0][1]);
        System.out.println("El asiento [0][0] es " + asientos[1][0]);
        System.out.println("El asiento [1][2] es " + asientos[1][1]);
    
    }
}